"""empty message

Revision ID: b8311742087f
Revises: d67737dfe7ff
Create Date: 2022-05-11 15:56:35.089946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8311742087f'
down_revision = 'd67737dfe7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('category_parents_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'])
    op.drop_column('category', 'parents_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parents_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_parents_id_fkey', 'category', 'category', ['parents_id'], ['id'])
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###
